### ISSUE TITLE
After updating to v0.4.0 ImxBatchNftTransfer stopped working 

### ISSUE THREAD

**Issue by basitcubix** [immutable/unity-immutable-sdk#120]
After updating the immutable sdk to v `0.4.0` i am getting this error on `ImxBatchNftTransfer` There is definitely issue related to json not being parsed properly as it’s clearly shown in the logs can you please help me with this?

```
2023/11/17 20:11:57.138 30111 30188 Info Unity [Passport Implementation] ImxBatchNftTransfer json: {}
2023/11/17 20:11:57.139 30111 30188 Info Unity [Browser Communications Manager] Call imxBatchNftTransfer (request ID: d08dd189-587f-4e3d-b187-2a466b664602, js: callFunction("{\"fxName\":\"imxBatchNftTransfer\",\"requestId\":\"d08dd189-587f-4e3d-b187-2a466b664602\",\"data\":\"{}\"}"))
2023/11/17 20:11:57.156 30111 30188 Info Unity [Browser Communications Manager] InvokeOnUnityPostMessage: {"responseFor":"imxBatchNftTransfer","requestId":"d08dd189-587f-4e3d-b187-2a466b664602","success":false,"error":"r.map is not a function","errorType":"TRANSFER_ERROR"}
2023/11/17 20:11:57.156 30111 30188 Info Unity [Browser Communications Manager] HandleResponse message: {"responseFor":"imxBatchNftTransfer","requestId":"d08dd189-587f-4e3d-b187-2a466b664602","success":false,"error":"r.map is not a function","errorType":"TRANSFER_ERROR"}
2023/11/17 20:11:57.162 30111 30188 Error Unity r.map is not a function
```

**Comment by nattb8** [comment]
@basitcubix Can you please tell me:
- The Unity version you are using
- What environment are you using (macOS or Windows)
- What platform are you trying to build for (Android/iOS/macOS/Windows)?

**Comment by nattb8** [comment]
@basitcubix Can you please try [version 0.4.1](https://github.com/immutable/unity-immutable-sdk/releases/tag/v0.4.1).
